name: PHP Tests

on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pcov
          coverage: pcov

      - name: Install root dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        run: |
          mkdir -p coverage
          vendor/bin/testo --coverage

      - name: Verify coverage report
        run: |
          php -m | grep -Ei 'pcov|xdebug'
          ls -la coverage
          test -f coverage/clover.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          files: ${{ github.workspace }}/coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: dragomano/Plugin-Loader
